name: Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3 
      with:
        username: "jonasbp"
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push
      uses: docker/build-push-action@v5 
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: jonasbp/aposta-ci:${{ github.sha }}
    - name: executing remote ssh commands using password 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_TEST }} 
        username: "ubuntu"
        key: ${{ secrets.KEY_TEST }} 
        port: 22
        script: |
          docker stop campeonato
          docker rm --force tabela
          docker run -d -p 8080:8080 --network=rede --name tabela jonasbp/tabela-ci:${{ github.sha }}
